#!/bin/bash
# Deployment helper script for AI Chat Bot

echo "AI Chat Bot Deployment Helper"
echo "=============================="

echo ""
echo "Step 1: Backend Deployment on Hugging Face Spaces"
echo "-----------------------------------------------"
echo "1. Go to https://huggingface.co/new-space"
echo "2. Create a new space with:"
echo "   - Name: Your preferred space name"
echo "   - SDK: Docker"
echo "   - Hardware: CPU (sufficient for this app)"
echo "   - Repository Type: Using Git integration"
echo "3. Point it to your GitHub repository containing this code"
echo "4. The space will automatically build and deploy"

echo ""
echo "Step 2: Frontend Deployment on Vercel"
echo "-------------------------------------"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'New Project' and import your repository"
echo "3. Configure the project with:"
echo "   - Framework: Next.js"
echo "   - Root Directory: frontend"
echo "4. Set environment variables in Vercel dashboard:"
echo "   - NEXT_PUBLIC_API_URL: URL of your deployed backend"
echo "5. Click 'Deploy'"

echo ""
echo "Environment Configuration:"
echo "--------------------------"
echo "Backend (Hugging Face Spaces):"
echo "- Automatically uses fallback configuration for demo deployment"
echo "- No additional configuration needed for demo"
echo ""
echo "Frontend (Vercel):"
echo "- NEXT_PUBLIC_API_URL: Your Hugging Face Space URL (e.g., https://username-space-name.hf.space)"

echo ""
echo "Testing:"
echo "--------"
echo "After deployment:"
echo "- Backend API: https://your-username.hf.space/docs"
echo "- Frontend: Your Vercel deployment URL"
echo ""

echo "For production use, consider updating to use PostgreSQL and real secrets."